// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListPorts() {
  return window['go']['main']['App']['ListPorts']();
}

export function SetPort(arg1) {
  return window['go']['main']['App']['SetPort'](arg1);
}
