// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetBuzzerLatencies():Promise<{[key: string]: number}>;

export function ListBuzzerIds():Promise<Array<string>>;

export function ListTeams():Promise<Array<main.Team>>;

export function ReadControllerState():Promise<any>;

export function SaveTeams(arg1:Array<main.Team>):Promise<void>;
