// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListPorts():Promise<Array<string>>;

export function SetPort(arg1:string):void;
